// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: primenumberdecomposition/primenumdecompb/primenumdecom.proto

package primenumdecompb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimeDecom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PrimeDecom) Reset() {
	*x = PrimeDecom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeDecom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeDecom) ProtoMessage() {}

func (x *PrimeDecom) ProtoReflect() protoreflect.Message {
	mi := &file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeDecom.ProtoReflect.Descriptor instead.
func (*PrimeDecom) Descriptor() ([]byte, []int) {
	return file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDescGZIP(), []int{0}
}

func (x *PrimeDecom) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PrimeDecomManyTimesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Primedecom *PrimeDecom `protobuf:"bytes,1,opt,name=primedecom,proto3" json:"primedecom,omitempty"`
}

func (x *PrimeDecomManyTimesRequest) Reset() {
	*x = PrimeDecomManyTimesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeDecomManyTimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeDecomManyTimesRequest) ProtoMessage() {}

func (x *PrimeDecomManyTimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeDecomManyTimesRequest.ProtoReflect.Descriptor instead.
func (*PrimeDecomManyTimesRequest) Descriptor() ([]byte, []int) {
	return file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeDecomManyTimesRequest) GetPrimedecom() *PrimeDecom {
	if x != nil {
		return x.Primedecom
	}
	return nil
}

type PrimeDecomManyTimesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PrimeDecomManyTimesResponse) Reset() {
	*x = PrimeDecomManyTimesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeDecomManyTimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeDecomManyTimesResponse) ProtoMessage() {}

func (x *PrimeDecomManyTimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeDecomManyTimesResponse.ProtoReflect.Descriptor instead.
func (*PrimeDecomManyTimesResponse) Descriptor() ([]byte, []int) {
	return file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDescGZIP(), []int{2}
}

func (x *PrimeDecomManyTimesResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_primenumberdecomposition_primenumdecompb_primenumdecom_proto protoreflect.FileDescriptor

var file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x64, 0x65, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x6e, 0x75, 0x6d, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x6e, 0x75, 0x6d, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x70, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x22, 0x24, 0x0a,
	0x0a, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x57, 0x0a, 0x1a, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f,
	0x6d, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x39, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d,
	0x64, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d,
	0x52, 0x0a, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x22, 0x35, 0x0a, 0x1b,
	0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x85, 0x01, 0x0a, 0x11, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63,
	0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x70, 0x0a, 0x13, 0x50, 0x72, 0x69,
	0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x12, 0x29, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x64, 0x65, 0x63, 0x6f, 0x6d,
	0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x4d, 0x61, 0x6e, 0x79, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x70, 0x72,
	0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x2e, 0x50, 0x72, 0x69, 0x6d,
	0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x2e,
	0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x64, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x6e,
	0x75, 0x6d, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDescOnce sync.Once
	file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDescData = file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDesc
)

func file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDescGZIP() []byte {
	file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDescOnce.Do(func() {
		file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDescData = protoimpl.X.CompressGZIP(file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDescData)
	})
	return file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDescData
}

var file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_goTypes = []interface{}{
	(*PrimeDecom)(nil),                  // 0: primenumdecom.PrimeDecom
	(*PrimeDecomManyTimesRequest)(nil),  // 1: primenumdecom.PrimeDecomManyTimesRequest
	(*PrimeDecomManyTimesResponse)(nil), // 2: primenumdecom.PrimeDecomManyTimesResponse
}
var file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_depIdxs = []int32{
	0, // 0: primenumdecom.PrimeDecomManyTimesRequest.primedecom:type_name -> primenumdecom.PrimeDecom
	1, // 1: primenumdecom.PrimeDecomService.PrimeDecomManyTimes:input_type -> primenumdecom.PrimeDecomManyTimesRequest
	2, // 2: primenumdecom.PrimeDecomService.PrimeDecomManyTimes:output_type -> primenumdecom.PrimeDecomManyTimesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_init() }
func file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_init() {
	if File_primenumberdecomposition_primenumdecompb_primenumdecom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeDecom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeDecomManyTimesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeDecomManyTimesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_goTypes,
		DependencyIndexes: file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_depIdxs,
		MessageInfos:      file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_msgTypes,
	}.Build()
	File_primenumberdecomposition_primenumdecompb_primenumdecom_proto = out.File
	file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_rawDesc = nil
	file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_goTypes = nil
	file_primenumberdecomposition_primenumdecompb_primenumdecom_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeDecomServiceClient is the client API for PrimeDecomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeDecomServiceClient interface {
	PrimeDecomManyTimes(ctx context.Context, in *PrimeDecomManyTimesRequest, opts ...grpc.CallOption) (PrimeDecomService_PrimeDecomManyTimesClient, error)
}

type primeDecomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeDecomServiceClient(cc grpc.ClientConnInterface) PrimeDecomServiceClient {
	return &primeDecomServiceClient{cc}
}

func (c *primeDecomServiceClient) PrimeDecomManyTimes(ctx context.Context, in *PrimeDecomManyTimesRequest, opts ...grpc.CallOption) (PrimeDecomService_PrimeDecomManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeDecomService_serviceDesc.Streams[0], "/primenumdecom.PrimeDecomService/PrimeDecomManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeDecomServicePrimeDecomManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeDecomService_PrimeDecomManyTimesClient interface {
	Recv() (*PrimeDecomManyTimesResponse, error)
	grpc.ClientStream
}

type primeDecomServicePrimeDecomManyTimesClient struct {
	grpc.ClientStream
}

func (x *primeDecomServicePrimeDecomManyTimesClient) Recv() (*PrimeDecomManyTimesResponse, error) {
	m := new(PrimeDecomManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeDecomServiceServer is the server API for PrimeDecomService service.
type PrimeDecomServiceServer interface {
	PrimeDecomManyTimes(*PrimeDecomManyTimesRequest, PrimeDecomService_PrimeDecomManyTimesServer) error
}

// UnimplementedPrimeDecomServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeDecomServiceServer struct {
}

func (*UnimplementedPrimeDecomServiceServer) PrimeDecomManyTimes(*PrimeDecomManyTimesRequest, PrimeDecomService_PrimeDecomManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeDecomManyTimes not implemented")
}

func RegisterPrimeDecomServiceServer(s *grpc.Server, srv PrimeDecomServiceServer) {
	s.RegisterService(&_PrimeDecomService_serviceDesc, srv)
}

func _PrimeDecomService_PrimeDecomManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeDecomManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeDecomServiceServer).PrimeDecomManyTimes(m, &primeDecomServicePrimeDecomManyTimesServer{stream})
}

type PrimeDecomService_PrimeDecomManyTimesServer interface {
	Send(*PrimeDecomManyTimesResponse) error
	grpc.ServerStream
}

type primeDecomServicePrimeDecomManyTimesServer struct {
	grpc.ServerStream
}

func (x *primeDecomServicePrimeDecomManyTimesServer) Send(m *PrimeDecomManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeDecomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "primenumdecom.PrimeDecomService",
	HandlerType: (*PrimeDecomServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeDecomManyTimes",
			Handler:       _PrimeDecomService_PrimeDecomManyTimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "primenumberdecomposition/primenumdecompb/primenumdecom.proto",
}
